import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { AiFillGithub, AiFillCodepenCircle } from "react-icons/ai"
import MyAvatar from '../src/components/MyAvatar'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Abru'sc</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section id="hero">
          <MyAvatar style={{width:"100%"}}/>
        </section>
        <section id="about">
          <h1 className="title">About</h1>
        </section>
        <section id="portfolio">
          <h1 className="title">Projects</h1>
        </section>
        <section id="contact">
          <h1 className="title">Get In Touch</h1>
        </section>
      </main>

      <footer className={styles.footer}>
        <a href="https://github.com/AbrarChowdhury">
          <AiFillGithub/>
        </a>
        <a href="https://codepen.io/abrar-shams-chowdhury"><AiFillCodepenCircle/></a>
      </footer>
    </div>
  )
}
