import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { AiFillGithub, AiFillCodepenCircle } from "react-icons/ai"
import MyAvatar from '../src/components/MyAvatar'
import { useEffect, useRef, useState } from 'react'
export default function Home() {
  const ref = useRef();
  const [xCord, setXCord] = useState(0);
  const [yCord, setYCord] = useState(0);
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    setLoading(false)
  }, [])

  const handleMouseMove = ({ clientX, clientY }) => {
    console.log("cx:", clientX)
    console.log("window:", ref.current.clientWidth)
    const x = ( clientX / ref.current.clientWidth * 100 - 50) // varries from -50 to 50
    const y = ( clientY / ref.current.clientHeight * 100 - 50) // varries from -50 to 50
    setXCord(x)
    setYCord(y)
  }


  
  return loading ? (
    <h1>Loading...</h1>
  ) : (
    <div className={styles.container}>
      <Head>
        <title>Abru'sc</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <style>@import url('https://fonts.googleapis.com/css2?family=Bitter:wght@300;400;500&display=swap');</style>
      </Head>
      <section id={styles.hero} ref={ref} onMouseMove={(e) => handleMouseMove(e)}>
        <MyAvatar x={xCord} y={yCord} />
        <div style={{height:"max-content"}}>
          <h1>
            Hi, my <br className={styles.lineBreak}/>name is <b>Abrar</b>.
          </h1>
        </div>
      </section>
      <main className={styles.main}>
        <section id="about">
          <h1 className="title">About</h1>
        </section>
        <section id="portfolio">
          <h1 className="title">Projects</h1>
        </section>
        <section id="contact">
          <h1 className="title">Get In Touch</h1>
        </section>
      </main>

      <footer className={styles.footer}>
        <a href="https://github.com/AbrarChowdhury">
          <AiFillGithub />
        </a>
        <a href="https://codepen.io/abrar-shams-chowdhury">
          <AiFillCodepenCircle />
        </a>
      </footer>
    </div>
  )
}
